// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avsc
 */
package avro

import (
	"io"
	"github.com/actgardner/gogen-avro/vm/types"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/compiler"
)

  
type BinaryObject struct {

	
	
		Type string
	

	
	
		Value []byte
	

}

func NewBinaryObject() (*BinaryObject) {
	return &BinaryObject{}
}

func DeserializeBinaryObject(r io.Reader) (*BinaryObject, error) {
	t := NewBinaryObject()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func DeserializeBinaryObjectFromSchema(r io.Reader, schema string) (*BinaryObject, error) {
	t := NewBinaryObject()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	if err != nil {
		return nil, err	
	}
	return t, err
}

func writeBinaryObject(r *BinaryObject, w io.Writer) error {
	var err error
	
	err = vm.WriteString( r.Type, w)
	if err != nil {
		return err			
	}
	
	err = vm.WriteBytes( r.Value, w)
	if err != nil {
		return err			
	}
	
	return err
}

func (r *BinaryObject) Serialize(w io.Writer) error {
	return writeBinaryObject(r, w)
}

func (r *BinaryObject) Schema() string {
	return "{\"fields\":[{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"bytes\"}],\"name\":\"BinaryObject\",\"namespace\":\"com.alibaba.dts.formats.avro\",\"type\":\"record\"}"
}

func (r *BinaryObject) SchemaName() string {
	return "com.alibaba.dts.formats.avro.BinaryObject"
}

func (_ *BinaryObject) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *BinaryObject) SetInt(v int32) { panic("Unsupported operation") }
func (_ *BinaryObject) SetLong(v int64) { panic("Unsupported operation") }
func (_ *BinaryObject) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *BinaryObject) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *BinaryObject) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *BinaryObject) SetString(v string) { panic("Unsupported operation") }
func (_ *BinaryObject) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *BinaryObject) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		
			return (*types.String)(&r.Type)
		
	
	case 1:
		
		
			return (*types.Bytes)(&r.Value)
		
	
	}
	panic("Unknown field index")
}

func (r *BinaryObject) SetDefault(i int) {
	switch (i) {
	
        
	
        
	
	}
	panic("Unknown field index")
}

func (_ *BinaryObject) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *BinaryObject) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *BinaryObject) Finalize() { }
