// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avsc
 */
package avro

import (
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/vm"
)

  
type EmptyObject int32

const (

	EmptyObjectNULL EmptyObject = 0

	EmptyObjectNONE EmptyObject = 1

)

func (e EmptyObject) String() string {
	switch e {

	case EmptyObjectNULL:
		return "NULL"

	case EmptyObjectNONE:
		return "NONE"

	}
	return "unknown"
}

func writeEmptyObject(r EmptyObject, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewEmptyObjectValue(raw string) (r EmptyObject, err error) {
	switch raw {

	case "NULL":
		return EmptyObjectNULL, nil

	case "NONE":
		return EmptyObjectNONE, nil

	}

	return -1, fmt.Errorf("invalid value for EmptyObject: '%s'", raw)
}
