// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avsc
 */
package avro

import (
	"io"
	"fmt"

	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
)


type UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum int
const (

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumField UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 0

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumInteger UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 1

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumCharacter UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 2

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumFloat UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 3

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDecimal UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 4

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestamp UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 5

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDateTime UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 6

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestampWithTimeZone UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 7

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryGeometry UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 8

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextGeometry UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 9

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryObject UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 10

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextObject UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 11

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumEmptyObject UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 12

	 UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumRecord UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum = 13

)

type UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord struct {

	Field *Field

	Integer *Integer

	Character *Character

	Float *Float

	Decimal *Decimal

	Timestamp *Timestamp

	DateTime *DateTime

	TimestampWithTimeZone *TimestampWithTimeZone

	BinaryGeometry *BinaryGeometry

	TextGeometry *TextGeometry

	BinaryObject *BinaryObject

	TextObject *TextObject

	EmptyObject EmptyObject

	Record *Record

	UnionType UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum
}

func writeUnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord(r *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord, w io.Writer) error {
	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType{
	
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumField:
		return writeField(r.Field, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumInteger:
		return writeInteger(r.Integer, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumCharacter:
		return writeCharacter(r.Character, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumFloat:
		return writeFloat(r.Float, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDecimal:
		return writeDecimal(r.Decimal, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestamp:
		return writeTimestamp(r.Timestamp, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumDateTime:
		return writeDateTime(r.DateTime, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTimestampWithTimeZone:
		return writeTimestampWithTimeZone(r.TimestampWithTimeZone, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryGeometry:
		return writeBinaryGeometry(r.BinaryGeometry, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextGeometry:
		return writeTextGeometry(r.TextGeometry, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumBinaryObject:
		return writeBinaryObject(r.BinaryObject, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumTextObject:
		return writeTextObject(r.TextObject, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumEmptyObject:
		return writeEmptyObject(r.EmptyObject, w)
        
	case UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnumRecord:
		return writeRecord(r.Record, w)
        
	}
	return fmt.Errorf("invalid value for *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord")
}

func NewUnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord() *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord {
	return &UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord{}
}

func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetBoolean(v bool) { panic("Unsupported operation") }
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetInt(v int32) { panic("Unsupported operation") }
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetFloat(v float32) { panic("Unsupported operation") }
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetBytes(v []byte) { panic("Unsupported operation") }
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetString(v string) { panic("Unsupported operation") }
func (r *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetLong(v int64) { 
	r.UnionType = (UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecordTypeEnum)(v)
}
func (r *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) Get(i int) types.Field {
	switch (i) {
	
	case 0:
		
		r.Field = NewField()
		
		
		return r.Field
		
	
	case 1:
		
		r.Integer = NewInteger()
		
		
		return r.Integer
		
	
	case 2:
		
		r.Character = NewCharacter()
		
		
		return r.Character
		
	
	case 3:
		
		r.Float = NewFloat()
		
		
		return r.Float
		
	
	case 4:
		
		r.Decimal = NewDecimal()
		
		
		return r.Decimal
		
	
	case 5:
		
		r.Timestamp = NewTimestamp()
		
		
		return r.Timestamp
		
	
	case 6:
		
		r.DateTime = NewDateTime()
		
		
		return r.DateTime
		
	
	case 7:
		
		r.TimestampWithTimeZone = NewTimestampWithTimeZone()
		
		
		return r.TimestampWithTimeZone
		
	
	case 8:
		
		r.BinaryGeometry = NewBinaryGeometry()
		
		
		return r.BinaryGeometry
		
	
	case 9:
		
		r.TextGeometry = NewTextGeometry()
		
		
		return r.TextGeometry
		
	
	case 10:
		
		r.BinaryObject = NewBinaryObject()
		
		
		return r.BinaryObject
		
	
	case 11:
		
		r.TextObject = NewTextObject()
		
		
		return r.TextObject
		
	
	case 12:
		
		
		return (*types.Int)(&r.EmptyObject)
		
	
	case 13:
		
		r.Record = NewRecord()
		
		
		return r.Record
		
	
	}
	panic("Unknown field index")
}
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) SetDefault(i int) { panic("Unsupported operation") }
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) AppendArray() types.Field { panic("Unsupported operation") }
func (_ *UnionFieldIntegerCharacterFloatDecimalTimestampDateTimeTimestampWithTimeZoneBinaryGeometryTextGeometryBinaryObjectTextObjectEmptyObjectRecord) Finalize()  { }
